const postTypes = {
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAIL: "GET_POSTS_FAIL",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAIL: "ADD_POST_FAIL",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_FAIL: "UPDATE_POST_FAIL",
  LIKE_UNLIKE_POST_SUCCESS: "LIKE_UNLIKE_POST_SUCCESS",
  LIKE_UNLIKE_POST_FAIL: "LIKE_UNLIKE_POST_FAIL",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAIL: "DELETE_POST_FAIL",
  POST_FAIL: "POST_FAIL",
  SET_LOADING_POSTS: "SET_LOADING_POSTS",
};

export default postTypes;
