const postTypes = {
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  LIKE_UNLIKE_POST_SUCCESS: "LIKE_UNLIKE_POST_SUCCESS",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  POST_FAIL: "POST_FAIL",
  SET_LOADING_POSTS: "SET_LOADING_POSTS",
};

export default postTypes;
