const notificationTypes = {
  GET_NOTIFICATIONS_SUCCESS: "GET_NOTIFICATIONS_SUCCESS",
  GET_NOTIFICATIONS_FAIL: "GET_NOTIFICATIONS_FAIL",
  ADD_NOTIFICATION: "ADD_NOTIFICATION",
  READ_NOTIFICATIONS_SUCCESS: "READ_NOTIFICATIONS_SUCCESS",
  READ_NOTIFICATIONS_FAIL: "READ_NOTIFICATIONS_FAIL",
  DELETE_NOTIFICATION_SUCCESS: "DELETE_NOTIFICAION_SUCCESS",
  DELETE_NOTIFICATION_FAIL: "DELETE_NOTIFICAION_FAIL",
  DELETE_NOTIFICATIONS_SUCCESS: "DELETE_NOTIFICAIONS_SUCCESS",
  DELETE_NOTIFICATIONS_FAIL: "DELETE_NOTIFICAIONS_FAIL",
};

export default notificationTypes;
