const commentTypes = {
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAIL: "ADD_COMMENT_FAIL",
  UPDATE_COMMENT_SUCCESS: "UPDATE_COMMENT_SUCCESS",
  UPDATE_COMMENT_FAIL: "UPDATE_COMMENT_FAIL",
  LIKE_UNLIKE_COMMENT_SUCCESS: "LIKE_UNLIKE_COMMENT_SUCCESS",
  LIKE_UNLIKE_COMMENT_FAIL: "LIKE_UNLIKE_COMMENT_FAIL",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAIL: "DELETE_COMMENT_FAIL",
  SET_LOADING_COMMENTS: "SET_LOADING_COMMENTS",
};

export default commentTypes;
